Following error is generated when I ran 01_generateEvents.sh

/globalhome/hxo752/HPC/anaconda3/envs/suppa/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
INFO:eventGenerator:Reading input data.
ERROR:__main__:Unknown error: (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x2aaacdc13540>)
